#!/bin/bash

# http://www.modmypi.com/blog/ds18b20-one-wire-digital-temperature-sensor-and-the-raspberry-pi
# Add the following line to /boot/config.txt
# dtoverlay=w1-gpio

# sudo apt-get install bc

#sudo modprobe w1-gpio
#sudo modprobe w1-therm

# CREATE TABLE `temperature` (
#  `id` int(11) NOT NULL AUTO_INCREMENT,
#  `sensor` int(11) DEFAULT NULL,
#  `value` double DEFAULT NULL,
#  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
#  `value1` double DEFAULT NULL,
#  `value2` double DEFAULT NULL,
#  `value3` double DEFAULT NULL,
#  `log` text,
#  PRIMARY KEY (`id`)
#)

# containing dir
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

while true; do

VAL=`"$DIR"/readtemp 28-000006b080be`

VAL1=`"$DIR"/readtemp 28-000006b18a9c`

VAL2=`"$DIR"/readtemp 10-000802dbc43f`


if [ "$VAL" == "" ]; then
  VAL="null"
fi

if [ "$VAL1" == "" ]; then
  VAL1="null"
fi

if [ "$VAL2" == "" ]; then
  VAL2="null"
fi

LOGTEXT=""

PROCTEMPTEXT=`sudo /opt/vc/bin/vcgencmd measure_temp`
PROCTEMP=`echo "$PROCTEMPTEXT" | cut -d'=' -f2 | cut -d"'" -f1`

mysql -u kovi -e "USE ajto; INSERT INTO temperature VALUES(null, 0, $VAL, null, $VAL1, $VAL2, $PROCTEMP, '$LOGTEXT');"
influx -database=loggers -execute "INSERT temperature room=$VAL,fridge=$VAL1,balcon=$VAL2,proc=$PROCTEMP"

sleep 59
done

