#!/bin/bash

#sudo modprobe w1-gpio
#sudo modprobe w1-therm

# CREATE TABLE temperature (id INT AUTO_INCREMENT KEY, sensor INT, value DOUBLE, date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

# containing dir
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

while true; do

VAL=`"$DIR"/readtemp 28-000006b080be`

VAL1=`"$DIR"/readtemp 28-000006b18a9c`

VAL2=`"$DIR"/readtemp 10-000802dbc43f`

LOGTEXT=""

PROCTEMPTEXT=`sudo /opt/vc/bin/vcgencmd measure_temp`
PROCTEMP=`echo "$PROCTEMPTEXT" | cut -d'=' -f2 | cut -d"'" -f1`

mysql -u kovi -e "USE ajto; INSERT INTO temperature VALUES(null, 0, $VAL, null, $VAL1, $VAL2, $PROCTEMP, '$LOGTEXT');"

sleep 59
done

